# general settings
name: LKDN_C56_A56_BSConvU_sandstone2D adan_ema_x4_DF2K_1000k
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: sandstone2D
    type: PairedImageDataset
    # dataroot_gt: datasets/DF2K/DF2K_train_HR_sub
    # dataroot_lq: datasets/DF2K/DF2K_train_LR_bicubic/X4_sub
   
    # (for lmdb)
    dataroot_gt: datasets/RockDataSet/DeepRockSR_train/sandstone2D/sandstone2D_train_HR
    dataroot_lq: datasets/RockDataSet/DeepRockSR_train/sandstone2D/sandstone2D_train_LR_default_X4
    meta_info_file: ./meta_info_sandstone2D_GT.txt
    filename_tmpl: '{}x4'
    io_backend:
      # type: disk
      # (for lmdb)
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val_1:
    name: sandstone2D
    type: PairedImageDataset
    dataroot_gt: ./datasets/RockDataSet/DeepRockSR_test/sandstone2D/sandstone2D_test_HR
    dataroot_lq: ./datasets/RockDataSet/DeepRockSR_test/sandstone2D/sandstone2D_test_LR_default_X4
    io_backend:
      type: disk

  #val_2:
    #name: Set14
    #type: PairedImageDataset
    #dataroot_gt: datasets/Set14/GTmod4
    #dataroot_lq: datasets/Set14/LRbicx4
    #io_backend:
      #type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/Urban100/GTmod4
  #   dataroot_lq: datasets/Urban100/LRbicx4
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: LKBN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_atten: 64
  num_block: 8
  upscale: 4
  num_in: 4
  conv: BSConvU
  upsampler: pixelshuffledirect

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    # type: Adam
    # lr: !!float 1e-3
    # weight_decay: 0
    # betas: [0.9, 0.99]

    type: Adan
    lr: !!float 5e-3
    betas: [0.98, 0.92, 0.99]
    weight_decay: 0
    foreach: true

  scheduler:
    type: MultiStepLR
    milestones: [20000]
    gamma: 0.5

  total_iter: 20000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 200
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 400
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
