name: Sandstone_Net400001_SR_X4
model_type: SRModel
scale: 4 # 2/3/4/8
num_gpu: 1 # or 4
manual_seed: 10

datasets:
  train:
    name: Sandstone
    type: PairedImageDataset
    dataroot_gt: ./datasets/RockDataSet/DeepRockSR_train/sandstone2D/sandstone2D_train_HR
    dataroot_lq: ./datasets/RockDataSet/DeepRockSR_train/sandstone2D/sandstone2D_train_LR_default_X4
    filename_tmpl: '{}x4'
    meta_info_file: ./meta_info_sandstone2D_GT.txt
    io_backend:
      type: disk

    gt_size: 256 #scale*48 or scale*64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Sandstone2D
    type: PairedImageDataset
    dataroot_gt: ./datasets/RockDataSet/DeepRockSR_test/sandstone2D/sandstone2D_test_HR
    dataroot_lq: ./datasets/RockDataSet/DeepRockSR_test/sandstone2D/sandstone2D_test_LR_default_X4
    io_backend:
      type: disk

# network structures
network_g:
  type: LDMN
  scale: 4 #or 3/4
  n_resblocks: 8 # 5 for MAN-tiny; 24 for MAN-light; 36 for MAN 
  n_resgroups: 1
  n_feats: 60 # 48 for MAN-tiny; 60 for MAN-light; 180 for MAN 

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
#     type: MultiStepLR
#     milestones: [800000, 1200000, 140000, 1500000]
#     gamma: 0.5

    type: CosineAnnealingRestartLR
    periods: [80000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 80000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 800
  save_img: false
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 2 # 2/3/4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 1600
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
